version: '3.4'

services:
    mysql:
        image: mysql:5.7.22
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "db_name"
            MYSQL_USER: "db_user"
            MYSQL_PASSWORD: "db_password"
        volumes:
            - database:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: "1"
            PMA_HOST: "mysql"
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        volumes:
            - /sessions

volumes:
    database:
