sequence:
    "Prepare environment":
        diff:
            ".gitignore.txt": ".gitignore"
    "Copy files":
        copy:
            "config/packages/dev/framework.yaml": "config/packages/dev/framework.yaml"
            "docker-compose.override.yml.dist": "docker-compose.override.yml.dist"
            "docker-compose.yml": "docker-compose.yml"
            "docker/nginx/backend_dev.conf": "docker/nginx/backend_dev.conf"
            "docker/nginx/default.conf": "docker/nginx/default.conf"
            "docker/php/xdebug.ini": "docker/php/xdebug.ini"
            "Dockerfile": "Dockerfile"
            "Dockerfile-nginx": "Dockerfile-nginx"
        replace:
            ".env.yaml": ".env"
            ".env.dist.yaml": ".env.dist"
