sequence:
    "Prepare environment":
        diff:
            ".gitignore.txt": ".gitignore"
    "Copy files":
        copy:
            "docker-compose.override.yml.dist": "docker-compose.override.yml.dist"
            "docker-compose.yml": "docker-compose.yml"
            "docker/nginx/backend_dev.conf.default": "docker/nginx/backend_dev.conf.default"
            "docker/nginx/default.conf": "docker/nginx/default.conf"
            "docker/nginx/Dockerfile": "docker/nginx/Dockerfile"
            "docker/php/app.crontab": "docker/php/app.crontab"
            "docker/php/xdebug.ini": "docker/php/xdebug.ini"
            "Dockerfile": "Dockerfile"
