parameters:
    env(ENV_database_host): 'mysql'
    env(ENV_database_name): 'project'
    env(ENV_database_password): 'project'
    env(ENV_database_port): '3306'
    env(ENV_database_user): 'project'

doctrine:
    dbal:
        url: 'mysql://%env(ENV_database_user)%:%env(ENV_database_password)%@%env(ENV_database_host)%:%env(ENV_database_port)%/%env(ENV_database_name)%'
