parameters:
    env(ENV_mailer_from_address): no-reply@acme.com
    env(ENV_mailer_from_name): No-reply

fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: App\Entity\User
    from_email:
        address: "%env(ENV_mailer_from_address)%"
        sender_name: "%env(ENV_mailer_from_name)%"
    service:
        mailer: fos_user.mailer.twig_swift

services:
    _defaults:
        autowire: true

    app.admin.user:
        class: App\Admin\UserAdmin
        arguments: [ ~, App\Entity\User, ~ ]
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users, group: Miscellaneous }

    App\Admin\UserAdmin: "@app.admin.user"
